services:
  db:
    image: postgres
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
      # - /opt/pet_project/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432